<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://www.car.com/new" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="car" 
targetNamespace="http://www.car.com/new">

  <wsdl:types>
    <xsd:schema>
    <xsd:import schemaLocation="car.xsd" namespace="http://www.car.com/new"/>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="portcarRequest">
    <wsdl:part name="carReq" element="tns:carRequest" />
  </wsdl:message>
  <wsdl:message name="CarResponse">
    <wsdl:part name="return" element="tns:carResponse" />
  </wsdl:message>
  
  <wsdl:portType name="CarStoreProvider">
    <wsdl:operation name="orderCar">
      <wsdl:input message="tns:portcarRequest"/>
      <wsdl:output message="tns:CarResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="CarStoreProviderBinding" type="tns:CarStoreProvider">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="orderCar">
      <soap:operation soapAction="http://www.car.com/new/orderCar"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
 
 
  <wsdl:service name="CarStoreProviderService">
    <wsdl:port binding="tns:CarStoreProviderBinding" name="CarStoreProviderServicePort">
      <soap:address location="http://localhost:29292/car-store/car"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
