
package com.car._new;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarStoreProviderService", targetNamespace = "http://www.car.com/new", wsdlLocation = "file:/Users/Harish/Desktop/Springproject/spring.webapp/src/main/webapp/WEB-INF/wsdl/car.wsdl")
public class CarStoreProviderService
    extends Service
{

    private final static URL CARSTOREPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARSTOREPROVIDERSERVICE_EXCEPTION;
    private final static QName CARSTOREPROVIDERSERVICE_QNAME = new QName("http://www.car.com/new", "CarStoreProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/Harish/Desktop/Springproject/spring.webapp/src/main/webapp/WEB-INF/wsdl/car.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARSTOREPROVIDERSERVICE_WSDL_LOCATION = url;
        CARSTOREPROVIDERSERVICE_EXCEPTION = e;
    }

    public CarStoreProviderService() {
        super(__getWsdlLocation(), CARSTOREPROVIDERSERVICE_QNAME);
    }

    public CarStoreProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARSTOREPROVIDERSERVICE_QNAME, features);
    }

    public CarStoreProviderService(URL wsdlLocation) {
        super(wsdlLocation, CARSTOREPROVIDERSERVICE_QNAME);
    }

    public CarStoreProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARSTOREPROVIDERSERVICE_QNAME, features);
    }

    public CarStoreProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarStoreProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarStoreProvider
     */
    @WebEndpoint(name = "CarStoreProviderServicePort")
    public CarStoreProvider getCarStoreProviderServicePort() {
        return super.getPort(new QName("http://www.car.com/new", "CarStoreProviderServicePort"), CarStoreProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarStoreProvider
     */
    @WebEndpoint(name = "CarStoreProviderServicePort")
    public CarStoreProvider getCarStoreProviderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.car.com/new", "CarStoreProviderServicePort"), CarStoreProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARSTOREPROVIDERSERVICE_EXCEPTION!= null) {
            throw CARSTOREPROVIDERSERVICE_EXCEPTION;
        }
        return CARSTOREPROVIDERSERVICE_WSDL_LOCATION;
    }

}
