
package com.car._new;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarStoreProvider", targetNamespace = "http://www.car.com/new")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarStoreProvider {


    /**
     * 
     * @param carReq
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.car.com/new/orderCar")
    @WebResult(name = "carResponse", targetNamespace = "http://www.car.com/new", partName = "return")
    public String orderCar(
        @WebParam(name = "carRequest", targetNamespace = "http://www.car.com/new", partName = "carReq")
        Car carReq);

}
